# Timeout in seconds before automatically booting
timeout: 0

# The name of your OS in the boot menu
/Obsidia
    # We use the limine boot protocol
    protocol: limine
    
    # Path to the ELF file we compiled with Zig
    kernel_path: boot():/kernel.elf
